hl.bind('SUPER + RETURN', hl.dsp.exec_cmd('ghostty'))
hl.bind('SUPER + SPACE', hl.dsp.exec_cmd('rofi -show drun filter "^" -no-fixed-num-lines'))
hl.bind('SUPER + BACKSPACE', hl.dsp.focus({ workspace = 'previous' }))
hl.bind('SUPER + TAB', hl.dsp.focus({ last = true }))
hl.bind('SUPER + Q', hl.dsp.window.close())
hl.bind('SUPER + W', hl.dsp.exec_cmd('pkill waybar || waybar'))
hl.bind('SUPER + S', hl.dsp.exec_cmd('hyprshot -m region --clipboard-only'))
hl.bind('SUPER + F', hl.dsp.window.fullscreen({ action = 'toggle' }))
hl.bind('SUPER + H', hl.dsp.focus({ direction = 'left' }))
hl.bind('SUPER + J', hl.dsp.focus({ direction = 'down' }))
hl.bind('SUPER + K', hl.dsp.focus({ direction = 'up' }))
hl.bind('SUPER + L', hl.dsp.focus({ direction = 'right' }))
hl.bind('SUPER + SHIFT + H', hl.dsp.window.move({ direction = 'left'}))
hl.bind('SUPER + SHIFT + J', hl.dsp.window.move({ direction = 'down'}))
hl.bind('SUPER + SHIFT + K', hl.dsp.window.move({ direction = 'up'}))
hl.bind('SUPER + SHIFT + L', hl.dsp.window.move({ direction = 'right'}))
hl.bind('SUPER + BRACKETLEFT', hl.dsp.layout('mfact -0.05'))
hl.bind('SUPER + BRACKETRIGHT', hl.dsp.layout('mfact +0.05'))
hl.bind('SUPER + BACKSLASH', hl.dsp.layout('mfact exact 0.5'))
hl.bind('SUPER + mouse:272', hl.dsp.window.drag(), { mouse = true })
hl.bind('SUPER + mouse:272', hl.dsp.window.resize(), { mouse = true })

hl.bind('SUPER + R', function()
    hl.exec_cmd('killall -q hyprpaper && hyprpaper')
    hl.exec_cmd('killall -q waybar && waybar')
end)

hl.bind('SUPER + ESCAPE', function()
    hl.dispatch(hl.dsp.exec_cmd('pidof hyprlock || hyprlock'))
    hl.dispatch(hl.dsp.dpms({ action = 'toggle' }))
end, { locked = true })

for index = 1, 10 do
    local key = index % 10
    hl.bind('SUPER + ' .. key, hl.dsp.focus({ workspace = index }))
    hl.bind('SUPER + SHIFT + ' .. key, hl.dsp.window.move({ workspace = index }))
end

hl.bind('XF86AudioRaiseVolume', hl.dsp.exec_cmd('wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+'), { locked = true, repeating = true })
hl.bind('XF86AudioLowerVolume', hl.dsp.exec_cmd('wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-'), { locked = true, repeating = true })
hl.bind('XF86AudioMute', hl.dsp.exec_cmd('wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'), { locked = true, repeating = true })
hl.bind('XF86AudioMicMute', hl.dsp.exec_cmd('wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle'), { locked = true, repeating = true })
hl.bind('XF86MonBrightnessUp', hl.dsp.exec_cmd('brightnessctl -e4 -n2 set 5%+'), { locked = true, repeating = true })
hl.bind('XF86MonBrightnessDown',hl.dsp.exec_cmd('brightnessctl -e4 -n2 set 5%-'), { locked = true, repeating = true })
hl.bind('XF86AudioNext', hl.dsp.exec_cmd('playerctl next'), { locked = true })
hl.bind('XF86AudioPause', hl.dsp.exec_cmd('playerctl play-pause'), { locked = true })
hl.bind('XF86AudioPlay', hl.dsp.exec_cmd('playerctl play-pause'), { locked = true })
hl.bind('XF86AudioPrev', hl.dsp.exec_cmd('playerctl previous'), { locked = true })
