accent = 0xFF727169
alternate_base = 0xFF727169
background = 0xFF0d0c0c
base = 0x00000000
bright_text = 0xFF727169
font_family = SauceCodePro Nerd Font Medium
font_size = 16
h1_size = 22
h2_size = 20
h3_size = 18
icon_theme = Papirus-Dark
monospace_font = SauceCodePro Nerd Font Mono
rounding_large = 2
rounding_small = 2
secondary_accent = 0xFFc8c093
small_font_size = 14
text = 0xFFc5c9c5
