background = 0xFF0d0c0c
base = 0x00000000
text = 0xFFc5c9c5
alternate_base = 0xFF727169
bright_text = 0xFF727169
accent = 0xFF727169
secondary_accent = 0xFFc8c093

# Fonts
font_family = SauceCodePro NF Propo
monospace_font = SauceCodePro NF Light
icon_theme = Papirus-Dark

h1_size = 22
h2_size = 20
h3_size = 18
font_size = 16
small_font_size = 14

rounding_large = 2
rounding_small = 2
