general {
    after_sleep_cmd = hyprctl dispatch "hl.dsp.dpms({ action = 'enable' })"
    lock_cmd = pidof hyprlock || hyprlock
}

listener {
    timeout = 1800
    on-timeout = hyprlock
}

listener {
    timeout = 2000
    on-resume = hyprctl dispatch "hl.dsp.dpms({ action = 'enable' })"
    on-timeout = hyprctl dispatch "hl.dsp.dpms({ action = 'disable' })"
}

listener {
    timeout = 2400,
    on-timeout = systemctl suspend
}
