[colors.primary]
background = "#181616"
foreground = "#c5c9c5"

[colors.normal]
black = "#0d0c0c"
blue = "#8ba4b0"
cyan = "#8ea4a2"
green = "#8a9a7b"
magenta = "#a292a3"
red = "#c4746e"
white = "#c8c093"
yellow = "#c4b28a"

[colors.bright]
black = "#a6a69c"
blue = "#7fb4ca"
cyan = "#7aa89f"
green = "#87a987"
magenta = "#938aa9"
red = "#e46876"
white = "#c5c9c5"
yellow = "#e6c384"

[colors.selection]
background = "#2d4f67"
foreground = "#c8c093"

[[colors.indexed_colors]]
color = "#b6927b"
index = 16

[[colors.indexed_colors]]
color = "#b98d7b"
index = 17

[cursor.style]
blinking = "Never"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.glyph_offset]
x = 0
y = 1

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Light Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Light"

[font.offset]
x = 0
y = 2

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ClearHistory"
key = "L"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[mouse]
hide_when_typing = true

[window]
dynamic_padding = true
opacity = 0.9
option_as_alt = "Both"

[window.padding]
x = 8
y = 8
