return {
    Constant = { ctermfg='green' },
    ColorColumn = { ctermbg='red', ctermfg='black' },
    Comment = { ctermfg='black', bold=true },
    CursorLine = { ctermbg='none' },
    DiffAdd = { ctermbg='green', ctermfg='black' },
    DiffChange = { ctermbg='yellow', ctermfg='black' },
    DiffDelete = { ctermbg='red', ctermfg='black' },
    DiffText = { ctermbg='blue', ctermfg='black' },
    Directory = { ctermfg='cyan' },
    Error = { ctermbg='none', ctermfg='red', bold=true },
    ErrorMsg = { ctermbg='none', ctermfg='red', bold=true },
    Folded = { ctermbg='black', ctermfg='white' },
    FoldColumn = { ctermbg='black', ctermfg='white' },
    Identifier = { ctermfg='white' },
    Info = { ctermfg='blue', bold=true },
    LineNr = { ctermfg='black', bold=true },
    MatchParen = { ctermbg='none', ctermfg='yellow', bold=true },
    MoreMsg = { ctermfg='green' },
    ModeMsg = { ctermfg='white' },
    NonText = { ctermbg='none', ctermfg='black', bold=true },
    Normal = { ctermbg='none', ctermfg='white' },
    NormalFloat = { ctermbg='none' },
    Number = { ctermfg='magenta' },
    Operator = { ctermfg='blue' },
    Pmenu = { ctermbg='black', ctermfg='white' },
    PmenuSbar = { ctermbg='black' },
    PmenuSel = { ctermbg='black', ctermfg='white', bold=true },
    PmenuThumb = { ctermbg='white', ctermfg='black', bold=true },
    PreProc = { ctermfg='blue' },
    Question = { ctermfg='yellow' },
    SignColumn = { ctermbg='none', ctermfg='white' },
    Special = { ctermfg='white' },
    SpecialKey = { ctermfg='cyan' },
    SpecialChar = { ctermfg='magenta' },
    SpellBad = { ctermbg='none', ctermfg='red', underline=true },
    SpellCap = { ctermbg='none', ctermfg='blue', underline=true },
    SpellRare = { ctermbg='none', ctermfg='magenta', underline=true },
    SpellLocal = { ctermbg='none', ctermfg='cyan', underline=true },
    Statement = { ctermfg='blue' },
    Title = { ctermfg='cyan', bold=true },
    Todo = { ctermbg='none', ctermfg='yellow' },
    Type = { ctermfg='blue' },
    Underlined = { ctermfg='cyan' },
    VertSplit = { ctermbg='none', ctermfg='black', bold=true },
    Visual = { ctermbg='black', bold=true },
    Warning = { ctermfg='yellow', bold=true },
    WarningMsg = { ctermfg='yellow' },
}
