return {
    TabLine = { ctermbg='black' },
    TabLineActive = { ctermbg='none', ctermfg='white' },
    TabLineActiveClean = { ctermbg='none', ctermfg='green', bold=true },
    TabLineActiveHasErrors = { ctermbg='none', ctermfg='red', bold=true },
    TabLineActiveHasInformation = { ctermbg='none', ctermfg='blue', bold=true },
    TabLineActiveHasWarnings = { ctermbg='none', ctermfg='yellow', bold=true },
    TabLineActiveIconModified = { ctermbg='none', ctermfg='yellow', bold=true },
    TabLineActiveIconReadOnly = { ctermbg='none', ctermfg='red', bold=true },
    TabLineActiveIconTerminal = { ctermbg='none', ctermfg='magenta', bold=true },
    TabLineActiveIconUnmodified = { ctermbg='none', ctermfg='green', bold=true },
    TabLineInactive = { ctermbg='black', ctermfg='white' },
    TabLineInactiveClean = { ctermbg='black', ctermfg='green', bold=true },
    TabLineInactiveHasErrors = { ctermbg='black', ctermfg='red', bold=true },
    TabLineInactiveHasInformation = { ctermbg='black', ctermfg='blue', bold=true },
    TabLineInactiveHasWarnings = { ctermbg='black', ctermfg='yellow', bold=true },
    TabLineInactiveIconModified = { ctermbg='black', ctermfg='yellow', bold=true },
    TabLineInactiveIconReadOnly = { ctermbg='black', ctermfg='red', bold=true },
    TabLineInactiveIconTerminal = { ctermbg='black', ctermfg='magenta', bold=true },
    TabLineInactiveIconUnmodified = { ctermbg='black', ctermfg='green', bold=true },
    TabLineInactiveIconModified = { ctermbg='black', ctermfg='yellow', bold=true },
}
