return {
    ['@boolean'] = { ctermfg='magenta' },
    ['@constant'] = { ctermfg='cyan' },
    ['@constant.builtin'] = { ctermfg='blue' },
    ['@constructor'] = { ctermfg='cyan' },
    ['@float'] = { ctermfg='magenta' },
    ['@function'] = { ctermfg='cyan' },
    ['@function.builtin'] = { ctermfg='cyan' },
    ['@function.call'] = { ctermfg='cyan' },
    ['@method'] = { ctermfg='cyan' },
    ['@method.call'] = { ctermfg='cyan' },
    ['@punctuation.bracket'] = { ctermfg='white' },
    ['@punctuation.delimiter'] = { ctermfg='white' },
    ['@tag'] = { ctermfg='blue' },
    ['@tag.attribute'] = { ctermfg='cyan' },
    ['@type'] = { ctermfg='cyan' },
    ['@type.builtin'] = { ctermfg='blue' },
    ['@type.definition'] = { ctermfg='cyan' },
    ['@type.qualifier'] = { ctermfg='blue' },
    ['@variable.builtin'] = { ctermfg='blue' },
}
