local beautiful = require('beautiful')
local filesystem = require('gears.filesystem')
local config_path = filesystem.get_configuration_dir()

local palette = {
    transparent = '#00000000',
    black = "#1d1f21",
    red = "#cc6666",
    green = "#b5bd68",
    yellow = "#f0c674",
    blue = "#81a2be",
    magenta = "#b294bb",
    cyan = "#8abeb7",
    white = "#c8c093",
    bright_black = "#727169",
    bright_red = "#d54e53",
    bright_green = "#b9ca4a",
    bright_yellow = "#e7c547",
    bright_blue = "#7aa6da",
    bright_magenta = "#c397d8",
    bright_cyan = "#70c0b1",
    bright_white = "#eaeaea",
}

beautiful.init({
    font = 'SauceCodePro 10, sans 10',
    bg_normal = palette.black,
    bg_focus = '#535d6c',
    bg_urgent = '#ff0000',
    bg_minimize = '#444444',
    fg_normal = palette.white,
    fg_focus = '#ffffff',
    fg_urgent = '#ffffff',
    fg_minimize = '#4c566a',
    border_width = 1,
    border_normal = '#0d0c0c',
    border_focus = '#c8c093',
    border_marked = '#91231c',
    taglist_fg_focus = palette.bright_white,
    taglist_fg_empty = palette.bright_black,
    taglist_fg_urgent = palette.yellow,
    taglist_fg_volatile = palette.red,
    taglist_bg_focus = palette.transparent,
    taglist_bg_urgent = palette.black,
    useless_gap = 4,
    palette = palette,
    wallpaper = config_path .. 'wallpapers/mountains.jpg',
    awesome_icon = config_path .. 'icons/arch.png',
    layout_fairh = config_path .. 'icons/fairhw.png',
    layout_fairv = config_path .. 'icons/fairvw.png',
    layout_floating = config_path .. 'icons/floatingw.png',
    layout_magnifier = config_path .. 'icons/magnifierw.png',
    layout_max = config_path .. 'icons/maxw.png',
    layout_fullscreen = config_path .. 'icons/fullscreenw.png',
    layout_tilebottom = config_path .. 'icons/tilebottomw.png',
    layout_tileleft = config_path .. 'icons/tileleftw.png',
    layout_tile = config_path .. 'icons/tilew.png',
    layout_tiletop = config_path .. 'icons/tiletopw.png',
    layout_spiral = config_path .. 'icons/spiralw.png',
    layout_dwindle = config_path .. 'icons/dwindlew.png',
    layout_cornernw = config_path .. 'icons/cornernww.png',
    layout_cornerne = config_path .. 'icons/cornernew.png',
    layout_cornersw = config_path .. 'icons/cornersww.png',
    layout_cornerse = config_path .. 'icons/cornersew.png',
})

return beautiful
